name: docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install latex
      run: sudo apt install -y latexmk texlive-latex-extra texlive-science texlive-lang-portuguese

    - name: Compile exams
      run: make exams/BDAD_exams.pdf
    - name: Upload exams
      uses: actions/upload-artifact@v2
      with:
        name: BDAD_exams.pdf
        path: exams/BDAD_exams.pdf
